### ISSUE TITLE
子评论bug

### ISSUE THREAD

**Issue by Zhao187** [Moosphan/CommentWithReplyView-master#1]
在原有的评论基础上，新建评论添加子评论没有显示回复内容
修改方法:
    CommentDetailBean.DataBean.CommentBean.ReplyListBean detailBean = new
                            CommentDetailBean.DataBean.CommentBean.ReplyListBean("小红",replyContent);
                    adapter.addTheReplyData(detailBean,groupPosition);
                    for (int i = 0; i < commentsList.size(); i++) {
                        expandableListView.expandGroup(i);
                    }

                    Toast.makeText(MainActivity.this,"回复成功",Toast.LENGTH_SHORT).show();
添加完成回复之后，再次展开ListView，显示子评论

**Comment by Moosphan** [comment]
@Zhao187 不好意思,现在才看到,多谢反馈,已经更新😆
