### ISSUE TITLE
有个问题  您给看看

### ISSUE THREAD

**Issue by Jeff-1203** [Moosphan/CommentWithReplyView-master#2]
回复的时候(不是评论)  底部弹出dialog 被键盘挡住了部分布局  发布按钮就被挡住了

**Comment by Moosphan** [comment]
@yinking1203 我这边并没有这种问题，我猜应该是你用的 `support` 包版本问题，26以上bottomsheetdialog中含有edittext会被软键盘覆盖一部分，而25就没有这个问题，你可以试一下，这应该是官方控件的一个小问题。
