### ISSUE TITLE
评论组件数据存储的问题

### ISSUE THREAD

**Issue by gaojingloudev** [Moosphan/CommentWithReplyView-master#5]
评论组件数据存储在android端还是调后端接口存储?

**Comment by Moosphan** [comment]
@gaojingloudev 数据源的问题因人而异，大部分应用肯定都是存储在云端，这样可以具备数据状态动态下发的能力

**Comment by gaojingloudev** [comment]
那也就是说我这边要自己写个后端接口用于评论数据的写入、读取、点赞数增加?

**Comment by Moosphan** [comment]
@gaojingloudev 没错
